# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Using npm ci to install exact versions and ignoring scripts
RUN npm ci --ignore-scripts

# Copy the rest of the code
COPY . .

# Build the project
RUN npm run build

# Expose a port if needed (optional, MCP typically communicates over stdio)
# EXPOSE 3000

# Command to run the MCP server
CMD [ "node", "dist/index.js" ]
